CP-42688: Collect NRPE config files
xenserver/status-report pull request #2
Opened 2023-05-04 04:33 UTC by xueqingz

Add two NRPE related config file in status report.

2023-05-04 08:45 UTC, lindig submitted a review, later dismissed

2023-05-04 08:51 UTC, andyhhp requested changes

2023-05-04 09:21 UTC, lindig submitted a review, later dismissed

2023-05-05 02:15 UTC, liulinC commented on xen-bugtool
> +NRPE_CUSTOMIZABLE_CONF = '/etc/nrpe.d'
Is this a file name or a directory name? 
it looks like a directory name, and if yes, `tree_output` should be used for this.

2023-05-06 01:51 UTC, liulinC approved these changes

2023-05-06 01:51 UTC, liulinC commented on xen-bugtool
>      file_output(CAP_XENSERVER_CONFIG, [CGRULES_CONF])
Presume the config file/directory is not large, so we do not need to enlarge `CAP_XENSERVER_CONFIG`
also presume the security level is conform to `CAP_XENSERVER_CONFIG`

2023-05-06 02:43 UTC, DeliZhangX approved these changes

2023-05-06 02:48 UTC, xueqingz commented on xen-bugtool
> +NRPE_CUSTOMIZABLE_CONF = '/etc/nrpe.d/xs.cfg'
Hi, @andyhhp. Could you please have a review again?

2023-05-09 08:44 UTC, rosslagerwall approved these changes

2023-05-09 11:05 UTC, andyhhp approved these changes

2023-05-10 01:23 UTC, merged