Private/bengangy/cp 46759
xenserver/status-report pull request #53
Opened 2024-01-15 11:38 UTC by BengangY

2024-01-16 10:23 UTC, BengangY commented
Failed in pre-commit check for no permission to create `/etc/snmp/*` file. Need to investigate it.

2024-01-18 08:33 UTC, BengangY commented
1 `/etc/snmp/snmp.xs.conf` format changed, so we need to replace sensitive string with the new format.
2 Add UT case for SNMP and the environment configure updates.
3 Update `.coveragerc` for the coverage should not cover the test files.

2024-01-18 09:12 UTC, DeliZhangX approved these changes

2024-01-18 20:42 UTC, bernhardkaindl requested changes
> 1 `/etc/snmp/snmp.xs.conf` format changed, so we need to replace sensitive string with the new format.

Does this PR use the new format?

2 Add UT case for SNMP and the environment configure updates.

What do you mean by "UT case"? I don't understand what you say.

> 3 Update `.coveragerc` for the coverage should not cover the test files.

Full NACK, on that. I desribe below why.

I pushed a new branch with a comment that you can cherry-pick into your PR.

With my commit cherry-picked, which does minor improvements for readability of the code, and also checks the output in the integration test case, I'd be able to approve - if you don't make furhter changes and only apply this commit on top. The PR that you can use to add my commit on your branch is here:

https://github.com/BengangY/status-report/pull/1

This is the commit for you to cherry-pick:

https://github.com/BengangY/status-report/commit/e2171045cd36b8536f8712655dcfb8affa34f650

And here is the diff between the two branches, so everyone can see it:
https://github.com/BengangY/status-report/compare/private/bengangy/CP-46759...xenserver-next:status-report:private/bengangy/CP-46759-fixup?expand=1#diff-73726d8e938c085ad9ff2315b623baf310c4e583b85eca33e33bf13124cae1f6R16

---

Hello @BengangY!

I would have had to write (and you to go through) many review comments for these tests.

That would take like a week of back and forth at least.

I'm in Cambridge next week on the know-how transfer week) so in real time this would take two weeks at least normally.

So instead:

Here is my pull request for your pull request to all the changes I need to request all at once.

If you apply it without any further changes, I'll be able to approve of the combined changes!

The other desirable changes and further updates can be done later.

I think when you review over the changes, that you may be able to understand why I made them, so I don't mention all small changes.

Removing the tests from coverage checking was not needed, and also the future module is not used.

You can add such changes temporarily, but push them.

The idea for near-100% code coverage of the tests is that you only knew that all tests ran completely, when the tests are 100% covered. I's a guard against broken testing! And keep it!

Broken testing where developers believed they tested something, but the test did nothing or not enough were the cause of a couple reverts of Python3 changes recently. We don't want that.

I hope that's understandable and clear and that you can agree.

While you develop, yes: do what you want, but afterwards restore the coverage check and run with it so, everybody confirms with it that the tests did actually run.

--
Further questions for the future:

What happens when the functions do when their input files do not look like they should ?(have invalid syntax where they want to filter!

---
TODO: The actual collection and filtering of files is not tested yet!

The unit test checks filtering the inputs using the individual funcs.

But:

With this commit, from an actual bugtool run,
we only test the non-existing files case!

Preferaby:

You should add the new config files as they are used now to tests/integration/dom0-template, then verify that the contents are the filtered contents.

However, without that final TODO done, we can already merge this and do the actual collection of the files in a new PR.

2024-01-21 09:36 UTC, BengangY commented
Hi @bernhardkaindl I have cherry-picked your commit https://github.com/BengangY/status-report/pull/1 into this PR, please merge this PR into the master. I will refine the test cases in a later PR. Thanks!

2024-01-21 10:33 UTC, merged

2024-01-21 11:01 UTC, bernhardkaindl commented
Squashed and merged this PR on top of the SNMP feature branch.

If you want to open a PR for merge to master:

There were significant updates to the master branch to add recoding the code coverage from the tests in tests/unit (other tests would need more updates to merge coverage files as they run bugtool in a new process).

Then, the tests in tests/unit were further improved to raise the code coverage from below 50% code coverage to above about 85%.

This was then the basis to update these 85% of the code to support Python 3.10, which the improved  unit tests confirm by always still passing in GitHub CI workflows of each merged PR.

Because these were significant changes, the SNMP feature branch now have some changes that may now be conflicting with the master.

This workflow can be improved if such feature branches are rebased to the master branch when concurrent work on a feature is being re-started after updates to master were done.

Now, before further changes, it would be recommended to rebase the SNMP branch to the master branch.

Even if it could be that it is not conflicting with master yet, the more time and commits accumulate the higher that probability may be.